clean:
	-del -f *.exe
all:  test 01_HelloWorld 02_PlayingWithCharacters 03_PrintingTokens 04_DynamicArrayinCBookShelfProblem 05_QueryingTheDocument 06_PrintingPatternUsingLoops 07_SortingArrayOfStrings 08_GetPermutations 09_NextPermutation

test: test.c
	gcc -o test test.c

01_HelloWorld: 01_HelloWorld.c
	gcc -o 01_HelloWorld 01_HelloWorld.c
	
02_PlayingWithCharacters: 02_PlayingWithCharacters.c
	gcc -o 02_PlayingWithCharacters 02_PlayingWithCharacters.c
	
03_PrintingTokens: 03_PrintingTokens.c
	gcc -o 03_PrintingTokens 03_PrintingTokens.c

04_DynamicArrayinCBookShelfProblem: 04_DynamicArrayinCBookShelfProblem.c
	gcc -o 04_DynamicArrayinCBookShelfProblem 04_DynamicArrayinCBookShelfProblem.c	
	
05_QueryingTheDocument: 05_QueryingTheDocument.c
	gcc -o 05_QueryingTheDocument 05_QueryingTheDocument.c

06_PrintingPatternUsingLoops: 06_PrintingPatternUsingLoops.c
	gcc -o 06_PrintingPatternUsingLoops 06_PrintingPatternUsingLoops.c

07_SortingArrayOfStrings: 07_SortingArrayOfStrings.c
	gcc -o 07_SortingArrayOfStrings 07_SortingArrayOfStrings.c

08_GetPermutations: 08_GetPermutations.c
	gcc -o 08_GetPermutations 08_GetPermutations.c
09_NextPermutation: 09_NextPermutation.c
	gcc -o 09_NextPermutation 09_NextPermutation.c