clean:
	-del -f *.exe
	
all: C_01_HelloWorld C_02_CopyInputToOutput C_03_WordCount C_04_StringLength C_05_LongestInputLine C_06_LeapYear C_07_StringToInteger C_08_ToLowerCase C_09_IsDigit C_10_RandomNumberGenerator

C_01_HelloWorld: C_01_HelloWorld.c
	gcc -o C_01_HelloWorld C_01_HelloWorld.c
	
C_02_CopyInputToOutput: C_02_CopyInputToOutput.c
	gcc -o C_02_CopyInputToOutput C_02_CopyInputToOutput.c
	
C_03_WordCount: C_03_WordCount.c
	gcc -o C_03_WordCount C_03_WordCount.c

C_04_StringLength: C_04_StringLength.c
	gcc -o C_04_StringLength C_04_StringLength.c

C_05_LongestInputLine: C_05_LongestInputLine.c
	gcc -o C_05_LongestInputLine C_05_LongestInputLine.c

C_06_LeapYear: C_06_LeapYear.c
	gcc -o C_06_LeapYear C_06_LeapYear.c

C_07_StringToInteger: C_07_StringToInteger.c
	gcc -o C_07_StringToInteger C_07_StringToInteger.c

C_08_ToLowerCase: C_08_ToLowerCase.c
	gcc -o C_08_ToLowerCase C_08_ToLowerCase.c

C_09_IsDigit: C_09_IsDigit.c
	gcc -o C_09_IsDigit C_09_IsDigit.c

C_10_RandomNumberGenerator: C_10_RandomNumberGenerator.c
	gcc -o C_10_RandomNumberGenerator C_10_RandomNumberGenerator.c
	
